# LifestealSMP config
Discord:
  # Enter bot token
  BotToken:

  Channel:

  Webhook:

  ConsoleChannel:

  LoggingChannel:

  Smp:

Key:

season-start-time: "2024-12-07T12:00:00[America/New_York]"




