name: LifestealSMP
version: '${project.version}'
main: newamazingpvp.lifestealsmp.LifestealSMP
api-version: '1.20'
authors: [NewAmazingPVP]
libraries:
  - com.fasterxml.jackson.core:jackson-databind:2.16.0
  - net.dv8tion:JDA:5.0.0-beta.17

commands:
  rules:
    description: Display the rules for this SMP season
    usage: /<command>
  setview:
    description: Set custom view and simulation distances
    usage: /setview <view_distance> <simulation_distance>
  recipes:
    description: View all the custom recipes of this lifesteal server
    usage: /recipes
  track:
    description: Track a player's location
    usage: /track <player>
    aliases: [compass]
  GiveSekhmetSet:
    description: Admins Only
    usage: /GiveSekhmetSet
    aliases: dontfuckingtrytorunthisifyouarenotaadmin
    default: op
  restart_with_warning:
    description: Admins Only RS server with a warning
    usage: /restart_with_warning
    default: op
  remHP:
    description: Removes HP Admins Only
    usage: /remHP
    default: op
  addHP:
    description: Adds HP Admins Only
    usage: /AddHP
    default: op
  LSwithdraw:
    description: Removes 1 heart
    usage: /LSwithdraw
    default: op
  startEndFight:
    description: Start End Fight with all presets
    usage: /startEndFight
    permission: lifestealSMP.admin
    default: op
  stopEndFight:
    description: Stop End Fight
    usage: /stopEndFight
    permission: lifestealSMP.admin
    default: op
  jailplayer:
    description: Use this to make a player a prisoner (troll command)
    usage: /jailplayer <name>
    permission: lifestealSMP.admin
    default: op
  reviveplayer:
    description: Revive an eliminated player!
    usage: /reviveplayer <name>
    permission: lifestealSMP.admin
    default: op
  customprefix:
    description: Custom prefix for player!
    usage: /customprefix <player> <prefix>
    permission: lifestealSMP.admin
    default: op
  vision:
    description: Enable full night vision
    usage: /vision
    aliases:
      - nightvision
  senddiscordmessage:
    description: Send message on discord!
    usage: /senddiscordmessage <msg> <channelID>
    permission: lifestealSMP.admin
    default: op
