name: LifestealSMP
version: '${project.version}'
main: newamazingpvp.lifestealsmp.LifestealSMP
api-version: '1.20'
authors: [NewAmazingPVP]
commands:
  rules:
    description: Display the rules for this SMP season
    usage: /<command>
  setview:
    description: Set custom view and simulation distances
    usage: /setview <view_distance> <simulation_distance>
  recipes:
    description: View all the custom recipes of this lifesteal server
    usage: /recipes
  track:
    description: Track a player's location
    usage: /track <player>
    aliases: [compass]
  GMS:
    description: Admins Only
    usage: /GMS
    aliases: dontfuckingtrytorunthisifyouarenotaadmin
  restart_with_warning:
    description: Admins Only RS server with a warning
    usage: /restart_with_warning
  remHP:
    description: Removes HP Admins Only
    usage: /remHP
  addHP:
    description: Adds HP Admins Only
    usage: /AddHP
  LSwithdraw:
    description: Removes 1 heart
    usage: /LSwithdraw
  startEndFight:
    description: Start End Fight with all presets
    usage: /startEndFight
  stopEndFight:
    description: Stop End Fight
    usage: /stopEndFight
  giveMontuHelm:
    description: Gives the custom montu helmet Admin Only
    usage: /giveMontuHelm
