name: LifestealSMP
version: '${project.version}'
main: newamazingpvp.lifestealsmp.LifestealSMP
api-version: '1.20'
authors: [NewAmazingPVP]
softdepend:
  - Essentials
libraries:
  - com.fasterxml.jackson.core:jackson-databind:2.16.0
  - net.dv8tion:JDA:5.0.0-beta.17
  - club.minnced:discord-webhooks:0.8.4
  - org.apache.logging.log4j:log4j-core:2.20.0

commands:
  rules:
    description: Display the rules for this SMP season
    usage: /<command>
  setview:
    description: Set custom view and simulation distances
    usage: /setview <view_distance> <simulation_distance>
    permission: lifestealSMP.admin
    default: op
  recipes:
    description: View all the custom recipes of this lifesteal server
    usage: /recipes
  track:
    description: Track a player's location
    usage: /track <player>
    aliases: [compass]
  GiveSekhmetSet:
    description: Admins Only
    usage: /GiveSekhmetSet
    permission: lifestealSMP.admin
    aliases: dontfuckingtrytorunthisifyouarenotaadmin
    default: op
  restart_with_warning:
    description: Admins Only RS server with a warning
    permission: lifestealSMP.admin
    usage: /restart_with_warning
    default: op
  remHP:
    description: Removes HP Admins Only
    usage: /remHP
    permission: lifestealSMP.admin
    default: op
  addHP:
    description: Adds HP Admins Only
    usage: /AddHP
    permission: lifestealSMP.admin
    default: op
  LSwithdraw:
    description: Removes 1 heart
    usage: /LSwithdraw
    aliases:
      - withdraw
  startEndFight:
    description: Start End Fight with all presets
    usage: /startEndFight
    permission: lifestealSMP.admin
    default: op
  stopEndFight:
    description: Stop End Fight
    usage: /stopEndFight
    permission: lifestealSMP.admin
    default: op
  jailplayer:
    description: Use this to make a player a prisoner (troll command)
    usage: /jailplayer <name>
    permission: lifestealSMP.admin
    default: op
  reviveplayer:
    description: Revive an eliminated player!
    usage: /reviveplayer <name>
    permission: lifestealSMP.admin
    default: op
  prefix:
    description: Set a custom prefix!
    usage: /prefix <prefix>
  vision:
    description: Enable full night vision
    usage: /vision
    aliases:
      - nightvision
  senddiscordmessage:
    description: Send message on discord!
    usage: /senddiscordmessage <msg> <channelID>
    permission: lifestealSMP.admin
    default: op
  shop:
    description: Get link for the shop
    usage: /shop
  discord:
    description: Get link for the discord server
    usage: /discord
  help:
    description: Useful commands for the SMP
    usage: /help
  guide:
    description: Guide tutorial book for SMP
    usage: /guide
  givecustomitem:
    description: Give custom item (admin only)!
    usage: /givecustomitem <player> <item>
    permission: lifestealSMP.admin
    default: op
  serverruntime:
    description: Check the server age/runtime!
    usage: /serverruntime
    aliases:
      - serverage
  team:
    description: Teams for the server
    usage: /team
    aliases:
      - tm
  ally:
    description: Ally with other teams
    usage: /ally
    aliases:
      - al
  gibIce:
    description: gives ice cube REMOVE THIS
    usage: /gibIce
    permission: lifestealSMP.admin
    default: op
  lockPlayer:
    description: Locks player and does not let them do anything (for moderation)
    usage: /lock <player>
    permission: lifestealSMP.admin
    default: op
  pingWars:
    description: PING WARS
    usage: /pingwars
    permission: lifestealSMP.admin
    default: op
  quickMaths:
    description: QUICK!!!!!!!!!!!!!
    usage: /quickmaths
    permission: lifestealSMP.admin
    default: op
  givebingocardtemp:
    description: gives bingo card TEMP
    usage: /givebingocardtemp
    permission: lifestealSMP.admin
    default: op
  generatenewbingogame:
    description: restarts bingo and makes new game WARNING ONLY USE WHEN NEEDED!
    usage: /generatenewbingogame
    permission: lifestealSMP.admin
    default: op