name: LifestealSMP
version: '${project.version}'
main: newamazingpvp.lifestealsmp.LifestealSMP
api-version: '1.20'
authors: [ NewAmazingPVP, Comet99 ]
folia-supported: true
softdepend:
  - Essentials
  - Chunky
libraries:
  #- com.fasterxml.jackson.core:jackson-databind:2.16.0
  - net.dv8tion:JDA:5.0.0-beta.17
  - club.minnced:discord-webhooks:0.8.4
  #- org.apache.logging.log4j:log4j-core:2.20.0

commands:
  register:
    description: Register for the tournament event
  rules:
    description: Display the rules for this SMP season
    usage: /<command>
  setview:
    description: Set custom view and simulation distances
    usage: /setview <view_distance> <simulation_distance>
    permission: lifestealSMP.admin
    default: op
  restart_with_warning:
    description: Admins Only RS server with a warning
    permission: lifestealSMP.admin
    usage: /restart_with_warning
    default: op
  startEndFight:
    description: Start End Fight with all presets
    usage: /startEndFight
    permission: lifestealSMP.admin
    default: op
  stopEndFight:
    description: Stop End Fight
    usage: /stopEndFight
    permission: lifestealSMP.admin
    default: op
  jailplayer:
    description: Use this to make a player a prisoner (troll command)
    usage: /jailplayer <name>
    permission: lifestealSMP.admin
    default: op
  prefix:
    description: Set a custom prefix!
    usage: /prefix <prefix>
  vision:
    description: Enable full night vision
    usage: /vision
    aliases:
      - nightvision
  senddiscordmessage:
    description: Send message on discord!
    usage: /senddiscordmessage <msg> <channelID>
    permission: lifestealSMP.admin
    default: op
  discord:
    description: Get link for the discord server
    usage: /discord
  help:
    description: Useful commands for the SMP
    usage: /help
  guide:
    description: Guide tutorial book for SMP
    usage: /guide
  serverruntime:
    description: Check the server age/runtime!
    usage: /serverruntime
    aliases:
      - serverage
  team:
    description: Teams for the server
    usage: /team
    aliases:
      - tm
  ally:
    description: Ally with other teams
    usage: /ally
    aliases:
      - al
  pingWars:
    description: PING WARS
    usage: /pingwars
    permission: lifestealSMP.admin
    default: op
  trade:
    description: Trade with players
    usage: /trade <player>
  betterban:
    description: Lets you ban someone with custom ban message
    usage: /betterban <player>
    permission: lifestealSMP.admin
    default: op
  unbanall:
    description: Lets you unban everybody (don't use this unless you know what you are doing)
    usage: /unbanall
    permission: lifestealSMP.admin
    default: op
  stat:
    description: Stat for nerds
    usage: /stat
    permission: lifestealSMP.admin
    default: op
  worldteleport:
    description: Teleport to a world
    usage: /worldteleport [world]
    permission: lifestealSMP.admin
    default: op
  tpuhc:
    description: Teleport to uhc world (during event)
    usage: /tpuhc
  spawn:
    description: Teleport to spawn to get unstuck
    usage: /spawn
  nonvanillamechanics:
    description: See all the non-vanilla mechanics in the server
    usage: /nonvanillamechanics
  showcustomtoast:
    description: Displays a custom toast to all players
    usage: /showcustomtoast [type] [icon] <message>
    permission: lifestealSMP.admin
    default: op
  showtoastwarn:
    description: Displays a custom toast to all players
    usage: /showtoastwarn <message>
    permission: lifestealSMP.admin
    default: op
  tournament:
    description: Command to manage the tournament event
    usage: /tournament <start|register|end>
    permission: lifestealSMP.admin
